version: '3.8'

services:
  backend:
    build: ./backend
    depends_on:
      - redis
      - postgres
    environment:
      - DATABASE_URL=postgresql://user:password@postgres:5432/todoapp?schema=public
    ports:
      - "4000:4000"
      - "4001:4001"  # GraphQL server
    volumes:
      - ./backend:/app  # Mount local code into the container
    networks:
      - app-network

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"  # Frontend UI
    depends_on:
      - backend
    volumes:
      - ./frontend:/usr/src/app  # Mount local code into the container
    networks:
      - app-network

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - app-network

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: todoapp
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - app-network

  nginx:
    build: ./nginx
    ports:
      - "80:80"  # Expose Nginx on port 80
    depends_on:
      - frontend
      - backend
    networks:
      - app-network

volumes:
  postgres-data:

networks:
  app-network:
    driver: bridge
